name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: install deps
        run: yarn
      - name: Run dev server
        run: yarn dev &
      - name: Wait until server is up
        run: sleep 45
      - name: run tests
        run: yarn test
